# Site settings

title: Salvius the Robot

description: >
  Salvius is a robotic prototype designed for learning.
  The robot's design is centered around a comprehensive
  API which makes it possible to get up and running in
  mere minutes. Developers can easily experiment with
  machine learning and kinematics for humanoid robots.
  A wide selection of plug and play hardware additions
  can be installed as well. Salvius has been built using
  a variety of recycled materials, making it simple and
  inexpensive to start developing.

short_description: Salvius is an open-source humanoid robot built on a minimal budget using recycled materials.

baseurl: "" # the subpath of your site, e.g. /blog/

# Base hostname & protocol for a site
url: http://salvius.org

email: gunthercx@gmail.com
twitter_username: salviusrobot
github_username:  gunthercox

permalink: /blog/:year/:month/:title/

collections:
  notes:
    output: true
  presentations:
    output: true
  spec:
    output: true

defaults:

  - scope:
      type: notes
    values:
      layout: paginated
      index_url: /notes/
      color_class: color-prestige

  - scope:
      type: presentations
    values:
      layout: presentation

  - scope:
      type: spec
    values:
      layout: page

  - scope:
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

gems:
  - jekyll-sitemap

exclude:
  - readme.md
  - Gemfile
  - scripts
